spring:
  application:
    name: visitor_identification
  ## Data repository configuration
  datasource:
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  rabbitmq:
    username: admin
    password: cas735
  cloud:
    function:
      definition:
        - handlePaymentStatusChanged
    stream:
      bindings:
        sendTransaction-out-0:
          destination: charge.event
        requestGateOpen-out-0:
          destination: access
        exitGateOpen-out-0:
          destination: exit
        handlePaymentStatusChanged-in-0:
          destination: payment.event

# logging level
logging.level:
  ca.mcmaster.cas735.acmepark.visitor_identification:
    adapter:  INFO # DEBUG for fine-grained trace
    business: INFO

# Port used by the server
server:
  port: 9091


# Start management infrastructure for health check and general infos
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /actuator

# Info about the service
info:
  application:
    description: '@project.description@'
    version:     '@project.version@'

# Asks the Service Registry client to register this instance as alive in the eureka registry
eureka:
  client:
    healthcheck:
      enabled: true
