spring:
  ## Data repository configuration
  datasource:
    url: jdbc:h2:file:/data/database-member-identification.h2 # persistent when used in docker.
  h2.console:
    enabled: false

  jpa:
    hibernate.ddl-auto: create-drop

  sql:
    init:
      mode: always


info:
  application:
    name: '@project.name@ (docker deployment)'

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/