# noinspection ComposeUnknownKeys
include:
  # Loading the technical infrastructure
  - ./../infrastructure/docker-compose.yml

services:
  member-identification:
    container_name: member-identification
    build:
      context: ../services/member_identification
    ports:
      - "9080:9080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy
