# noinspection ComposeUnknownKeys
include:
  # Loading the technical infrastructure
  - ./../infrastructure/docker-compose.yml

services:
  member-identification:
    container_name: member-identification
    build:
      context: ../services/member_identification
    ports:
      - "9090:9090"
    volumes:
      - ./data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  visitor-identification:
    container_name: visitor-identification
    build:
      context: ../services/visitor-identification
    ports:
      - "9091:9091"
    volumes:
      - ./data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  lot-management:
    container_name: lot-management
    build:
      context: ../services/lot_management
    ports:
      - "9093:9093"
    volumes:
      - ./data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy
