# noinspection ComposeUnknownKeys
include:
  # Loading the technical infrastructure
  - ./../infrastructure/docker-compose.yml

services:
  member-identification:
    container_name: member-identification
    build:
      context: ../services/member_identification
    ports:
      - "9090:9090"
    volumes:
      - ./data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  visitor-identification:
    container_name: visitor-identification
    build:
      context: ../services/visitor_identification
    ports:
      - "9091:9091"
    volumes:
      - ./data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  lot-management:
    container_name: lot-management
    build:
      context: ../services/lot_management
    ports:
      - "9093:9090"
    volumes:
      - ./data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  parking_enforcement:
    container_name: parking-enforcement
    build:
      context: ../services/parking_enforcement
    ports:
      - "9080:9080"
    volumes:
      - ./data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  payment_processing:
    container_name: payment-processing
    build:
      context: ../services/payment_processing
    ports:
      - "9081:9080"
    volumes:
      - ./data:/data
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy