spring:
  application:
    name: service_registry

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health
      base-path: /actuator

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
